theme: jekyll-theme-minimal
title: Gabriele La Malfa | Safe & Trusted AI
description: PhD candidate at Kingâ€™s College London & Imperial College London focusing on fairness in multi-agent systems and socio-technical AI.
