theme: jekyll-theme-minimal
title: Gabriele La Malfa | Safe & Trusted AI
description: I am a PhD candidate at Kingâ€™s College London focusing on human-value alignment (fairness) in multi-agent systems and multi-agent reinforcement learning (MARL). I like art, have a look at my oil pastel drawings!!
